version: '3'

services:
  web:
    image: nginx:1.15
    restart: always
    volumes:
      - "./public:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    labels:
      - "traefik.frontend.rule=Host: docker.xy2z.io"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
    networks:
      - web

networks:
  web:
    external: true
